---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-

  # Target: where our play will run and options it will run with
  hosts: localhost
  connection: local
  gather_facts: false

  # Task: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:

    - name: Create a security group in AWS for SSH access and HTTP
      ec2_group:
         name: staging
         description: Ansible Security Group
         region: us-east-1
         rules:
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 8082
              to_port: 8082
              cidr_ip: 0.0.0.0/0

    - name: Provision a set of instances
      ec2:
         key_name: softworldkey
         group: ansible
         instance_type: t2.micro
         image:  ami-6871a115
         region: us-east-1         
         wait: true
         exact_count: 1
         count_tag:
            Name: staging
         instance_tags:
            Name: staging
      ignore_errors: true
      register: ec2    
      
      
    - name: waiting
      pause: minutes=6
  

    - name: Refresh inventory to ensure new instances exist in inventory
      meta: refresh_inventory
      
  # Task: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks     
    
-

  # Target: where our play will run and options it will run with
  hosts: all
  vars:
      ansible_user: ec2-user
      ansible_become: true

  # Roles: list of roles to be imported into the play
  roles:
    - docker

# Three dots indicate the end of a YAML document
...
